# Generated by Django 3.1.4 on 2021-06-25 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='category',
            field=models.CharField(choices=[('E', 'Earth Creds'), ('S', 'Regular Creds')], default='Earth Creds', max_length=30),
        ),
        migrations.AlterField(
            model_name='user',
            name='category',
            field=models.CharField(choices=[('J', 'Junior'), ('A', 'Adult'), ('S', 'Senior')], default='Junior', max_length=20),
        ),
    ]
