# Generated by Django 3.1.4 on 2021-07-03 08:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20210702_1517'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='color',
            field=models.CharField(default='#ffffff', max_length=7),
        ),
        migrations.AlterField(
            model_name='activity',
            name='category',
            field=models.CharField(choices=[('S', 'Regular Creds'), ('E', 'Earth Creds')], default='Earth Creds', max_length=30),
        ),
        migrations.AlterField(
            model_name='user',
            name='category',
            field=models.CharField(choices=[('J', 'Junior'), ('S', 'Senior'), ('A', 'Adult')], default='Junior', max_length=20),
        ),
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=60)),
                ('amount', models.IntegerField(default=1)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='costs', to='api.activity')),
            ],
        ),
    ]
