# Generated by Django 3.1.4 on 2021-07-03 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20210703_1414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='service_type',
            field=models.CharField(choices=[('R', 'Request'), ('O', 'Offer ')], default='Offer', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='category',
            field=models.CharField(choices=[('A', 'Adult'), ('S', 'Senior'), ('J', 'Junior')], default='Junior', max_length=20),
        ),
    ]
