# Generated by Django 3.1.4 on 2021-07-06 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20210703_1555'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='founder_name',
            field=models.CharField(default='hello', max_length=20),
        ),
        migrations.AlterField(
            model_name='activity',
            name='category',
            field=models.CharField(choices=[('E', 'Earth Creds'), ('S', 'Regular Creds')], default='Earth Creds', max_length=30),
        ),
        migrations.AlterField(
            model_name='activity',
            name='service_type',
            field=models.CharField(choices=[('O', 'Offer '), ('R', 'Request')], default='Offer', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='category',
            field=models.CharField(choices=[('S', 'Senior'), ('A', 'Adult'), ('J', 'Junior')], default='Junior', max_length=20),
        ),
    ]
