# Generated by Django 3.1.4 on 2021-07-10 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20210706_1929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='category',
            field=models.CharField(choices=[('S', 'Regular Creds'), ('E', 'Earth Creds')], default='Earth Creds', max_length=30),
        ),
        migrations.AlterField(
            model_name='activity',
            name='description',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='user',
            name='category',
            field=models.CharField(choices=[('J', 'Junior'), ('S', 'Senior'), ('A', 'Adult')], default='Junior', max_length=20),
        ),
    ]
